//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using Models;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text.RegularExpressions;
    using System.Web;
    public partial class Dictionaries
    {
        private string RandomFilename()
        {
            Random random = new Random();

            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            return new string(Enumerable.Repeat(chars, 10)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public Dictionaries()
        {
            // random
            Path = RandomFilename() + ".po";

        }
        public int Id { get; set; }
        public string DictionaryName { get; set; }
        public string SourceLanguage { get; set; }
        public string Path { get; set; }

        public HttpPostedFileBase Files { get; set; }

        public void upload(Dictionaries po)
        {
            try
            {
                if (Files.ContentLength > 0)
                {
                    //var fileName = System.IO.Path.GetFileName(file.FileName);
                    var path = System.IO.Path.Combine(HttpContext.Current.Server.MapPath("~/Content/dictionaries"), Path);
                    Files.SaveAs(path);

                    //po.createDict(Path, "pl");
                    po.createDict(Path, "fr");
                    //po.createDict(Path, "de");
                }
            }
            catch (NullReferenceException)
            {
                // throw...
            }

        }

        private string translate(string word, string destLanguage)
        {
            string url = "http://api.microsofttranslator.com/v2/Http.svc/Translate?text=" + word + "&from=&to=" + destLanguage + "&appId=6CE9C85A41571C050C379F60DA173D286384E0F2";
            WebRequest webRequest = WebRequest.Create(url);
            webRequest.Method = "GET";
            WebResponse webResp = webRequest.GetResponse();

            Stream strm = webResp.GetResponseStream();
            StreamReader reader = new System.IO.StreamReader(strm);

            return Regex.Replace(reader.ReadToEnd().ToString(), @"<[^>]+>|&nbsp;", "").Trim();
        }

        private void createDict(string sourcefileName, string destLanguage)
        {
            var fileContents = System.IO.File.ReadAllLines(HttpContext.Current.Server.MapPath(@"~/Content/dictionaries/" + sourcefileName));

            string[] newFile = new string[fileContents.Length];

            //Dictionary<string, string> dictionary;

            for (int i = 0; i < fileContents.Length; i++)
            {
                if (fileContents[i][0].Equals('"'))
                    newFile[i] = fileContents[i];
                else
                {
                    // msgid
                    if (fileContents[i].Contains("msgid"))
                        newFile[i] = "msgid \"" + fileContents[i].Substring(7).Trim('"') + "\"";
                    // msgstr 
                    else
                        newFile[i] = "msgstr \"" + translate(fileContents[i].Substring(8).Trim('"'), destLanguage) + "\"";
                }

                //Debug.WriteLine(newFile[i]);
            }

            System.IO.File.WriteAllLines(HttpContext.Current.Server.MapPath(@"~/Content/dictionaries/" + destLanguage + "-source_" + sourcefileName), newFile);
        }
    }
}
